/**
 * Zod Schema for social_event
 * 
 * Auto-generated by Contract Sync Generator v1.0.0
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * 
 * Generated: 2026-03-01T17:19:23.227Z
 */

import { z } from 'zod';

export const SocialEventSchema = z.object({
  eventName: z.string().max(100),
  location: z.string().max(100),
  currentEvent: z.number().optional(),
  zonesOfActivity: z.array(z.unknown()).min(1),
  guestList: z.array(z.unknown()).min(3),
  topicsOfConversation: z.array(z.unknown()).optional(),
  eventSequence: z.array(z.unknown()).min(1)
});

export type SocialEventFormData = z.infer<typeof SocialEventSchema>;

export default SocialEventSchema;
