/**
 * TypeScript Types for social_event
 * 
 * Auto-generated by Contract Sync Generator v1.0.0
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * 
 * Generated: 2026-03-01T17:19:23.227Z
 */

/**
 * Field definitions for social_event form.
 * Maps field IDs to their TypeScript types.
 */
export interface SocialEventFields {
  /** Event Name - - */
  eventName: string;
  /** Location - - */
  location: string;
  /** Current Event Stage - - */
  currentEvent?: number;
  /** Zones of Activity - - */
  zonesOfActivity: unknown[];
  /** Guest List - - */
  guestList: unknown[];
  /** Topics of Conversation - - */
  topicsOfConversation?: unknown[];
  /** Event Sequence - - */
  eventSequence: unknown[];
}

/**
 * Field IDs as a union type for type-safe field access.
 */
export type SocialEventFieldId = 
  | 'eventName'
  | 'location'
  | 'currentEvent'
  | 'zonesOfActivity'
  | 'guestList'
  | 'topicsOfConversation'
  | 'eventSequence';

/**
 * Required field IDs for social_event.
 */
export type SocialEventRequiredFieldId = 
  | 'eventName'
  | 'location'
  | 'zonesOfActivity'
  | 'guestList'
  | 'eventSequence';

/**
 * Optional field IDs for social_event.
 */
export type SocialEventOptionalFieldId = 
  | 'currentEvent'
  | 'topicsOfConversation';

