export interface AIPersonality {
    // Big Five (OCEAN) scores from 0-100
    openness: number;
    conscientiousness: number;
    extraversion: number;
    agreeableness: number;
    neuroticism: number;
    // A one-sentence summary of the AI's core identity or role-playing directive.
    persona: string;
    // A short biography/backstory generated by the user or AI
    biography: string;
}

export interface AIProfileTemplate {
    name: string;
    personality: AIPersonality;
}

export type ConnectionStatus = 'connecting' | 'connected' | 'disconnected';

export interface Player {
    playerNumber: number;
    name: string;
    isOnline: boolean;
    password?: string;
    deityCount?: number;
    isAi: boolean;
    aiPersonality?: AIPersonality;
    playStyle?: 'Standard' | 'Asymmetric' | 'Avatar';
}
