import React from 'react';

export interface Era {
  id: number;
  name: string;
  icon: string;
}

export type EraStatus = 'completed' | 'current' | 'locked' | 'available';
export type View = 'eras' | 'elements';
export type GameState = 'setup' | 'player_selection' | 'playing' | 'loading_feed' | 'lobby' | 'ai_configuration' | 'finished';
export type GameRole = 'player' | 'observer';
export type ConnectionStatus = 'connecting' | 'connected' | 'disconnected';

export interface AIPersonality {
    // Big Five (OCEAN) scores from 0-100
    openness: number;
    conscientiousness: number;
    extraversion: number;
    agreeableness: number;
    neuroticism: number;
    // A one-sentence summary of the AI's core identity or role-playing directive.
    persona: string;
    // A short biography/backstory generated by the user or AI
    biography: string;
}

export interface AIProfileTemplate {
    name: string;
    personality: AIPersonality;
}

export interface GameSettings {
  players: number;
  aiPlayers: number;
  length: 'Short' | 'Standard' | 'Long' | 'Epic';
  turnDuration: number;
}

export interface AppSettings {
    markdownFormat: 'regular' | 'homebrewery';
}

export interface Player {
    playerNumber: number;
    name:string;
    isOnline: boolean;
    password?: string;
    deityCount?: number;
    isAi: boolean;
    aiPersonality?: AIPersonality;
    playStyle?: 'Standard' | 'Asymmetric' | 'Avatar';
}

export interface Resource {
    id: string;
    name: string;
    type: 'mineral' | 'flora' | 'fauna' | 'magical' | 'other';
    properties: string;
    symbol: string;
}

export interface Deity {
    id: string;
    name: string;
    domain: string;
    symbol: string; // Descriptive text
    emoji: string;  // Visual emoji for map
    description: string;
}

export interface Location {
    id: string;
    name: string;
    siteType: string;
    description: string;
    symbol: string;
    deityId?: string; // ID of the associated Deity ElementCard
}

export interface Faction {
    id: string;
    name: string;
    race: string;
    symbolName: string; // From the rulebook table, e.g., "Flame", "Horse"
    emoji: string;      // Visual emoji for the map, e.g., "🔥", "🐎"
    color: string;
    theme: string;
    description: string;
    leaderName: string;
    capitalName?: string; // Name of the capital city
    isNeighbor: boolean;
    neighborType?: string; // The specific type from the neighbor table, e.g., "Tribe or Clan"
    industry?: string;
    industryDescription?: string;
}

export interface Settlement {
    id: string;
    name: string;
    purpose: string;
    description: string;
    factionId?: string; // ID of the owning Faction ElementCard
}

export interface Event {
    id: string;
    name: string;
    description: string;
    factionId?: string; // For linking neighbor development events
}

export interface Character {
    id: string;
    name: string;
    description: string;
    factionId?: string;
}

export interface War {
    id: string;
    name: string;
    description: string;
    attackers: string[];
    defenders: string[];
}

export interface Monument {
    id: string;
    name: string;
    description: string;
    locationId?: string;
}


export interface ElementCard {
    id: string;
    type: 'Resource' | 'Deity' | 'Location' | 'Faction' | 'Settlement' | 'Event' | 'Character' | 'War' | 'Monument';
    name: string;
    owner: number; // playerNumber
    era: number;
    data: Resource | Deity | Location | Faction | Settlement | Event | Character | War | Monument;
    isDebug?: boolean;
    createdYear?: number;
    creationStep?: string;
}

// Props for new modular edit forms
export interface ElementFormProps<T> {
    data: T;
    onDataChange: (newData: Partial<T>) => void;
    isReadOnly: boolean;
}

export interface EraButtonProps {
  era: Era;
  status: EraStatus;
  onClick?: (eraId: number) => void;
}

export interface GameSetupProps {
    onStart: (settings: GameSettings) => void;
    onDebug?: () => void;
    onImport: (file: File) => void;
    onImportFromFeed: (url: string) => void;
    onBrowseLobby: () => void;
}

export interface AiPlayerSetupProps {
    gameSettings: GameSettings;
    onComplete: (players: Player[]) => void;
    onBack: () => void;
}

export interface PlayerSelectionProps {
    players: Player[];
    onSelect: (playerNumber: number, playerName: string, password?: string) => void;
    onJoinAsObserver: () => void;
}

// FIX: Added missing ProfileProps interface.
export interface ProfileProps {
    onBack: () => void;
}

export interface PlayerStatusProps {
    players: Player[];
    currentPlayer: Player | null;
    isDebugMode: boolean;
    onSwitchPlayer: (playerNumber: number) => void;
    onLogOff: () => void;
}

export interface AppLayoutProps {
    // These props are now removed as they will be provided by context.
}

export interface NavigationHeaderProps {
    // Props removed, will use context
}

export interface SettingsModalProps {
    isOpen: boolean;
    onClose: () => void;
    currentSettings: AppSettings;
    onSave: (settings: AppSettings) => void;
    gameSettings: GameSettings | null;
}

export interface DebugModalProps {
    isOpen: boolean;
    onClose: () => void;
    onPrepopulateEra: (eraId: number, playerNumber: number) => void;
    players: Player[];
    currentPlayer: Player | null;
    isEraNavigationUnlocked: boolean;
    onToggleEraNavigationLock: () => void;
}

export interface EmojiPickerProps {
    isOpen: boolean;
    onClose: () => void;
    onSelect: (emoji: string) => void;
    triggerRef: React.RefObject<HTMLElement>;
}

// Types for Era I: Age of Creation Gameplay State
export type GeographyType = 'Savanna' | 'Wetlands' | 'Hills' | 'Lake' | 'River' | 'Forest' | 'Mountains' | 'Desert' | 'Jungle' | 'Canyon' | 'Volcano';

export interface GeographyFeature {
    id: number;
    type: GeographyType | '';
    landmassIndex: number | '';
}

export interface EraCreationState {
    landmassType: string;
    featureCount: number;
    features: GeographyFeature[];
    advice: string;
    isLoading: boolean;
    error: string;
    userInputAdvice?: string;
}

export interface CompletionTrackerProps {
   // Props removed, will use context
}

export interface EraCreationContextType extends EraCreationState {
    setState: (state: Partial<EraCreationState> | ((prevState: EraCreationState) => Partial<EraCreationState>)) => void;
    handleFeatureChange: (id: number, field: 'type' | 'landmassIndex', value: string | number) => void;
    getAIAdvice: () => Promise<void>;
}

export interface EraDiscoveryContentProps {
    currentPlayer: Player | null;
    elements: ElementCard[];
    onCreateElement: (element: Omit<ElementCard, 'id'>, createdYear?: number, creationStep?: string) => void;
    onUpdateElement: (element: ElementCard) => void;
    onDeleteElement: (elementId: string) => void;
    appSettings: AppSettings;
    onExportElementHtml: (element: ElementCard) => void;
    onExportMarkdown: (element: ElementCard) => void;
    gameSettings: GameSettings | null;
}

export interface EraUIState {
    eraOne: { gameplayStep: 'geography' | 'resources' };
    eraTwo: { gameplayStep: 'setup' | 'pantheon' | 'sites' };
    eraThree: { gameplayStep: 'faction' | 'neighbor' | 'settlement' | 'complete' };
    eraFour: { gameplayStep: 'exploration' | 'colonization' | 'prosperity' };
    eraFive: { gameplayStep: 'expansion' | 'neighbors' };
    eraSix: { gameplayStep: 'events' | 'landmarks' | 'omen' };
}