
export const PRESET_COLORS = [
  { name: 'Red', hex: '#f87171' },
  { name: 'Blue', hex: '#60a5fa' },
  { name: 'Green', hex: '#4ade80' },
  { name: 'Yellow', hex: '#fbbf24' },
  { name: 'Purple', hex: '#c084fc' },
  { name: 'Teal', hex: '#2dd4bf' },
  { name: 'Orange', hex: '#fb923c' },
  { name: 'Pink', hex: '#f472b6' },
];

export const DIVINE_DOMAINS = [
  { id: 'FORGE', icon: 'build', tone: 'Industrial' },
  { id: 'LIFE', icon: 'eco', tone: 'Vital' },
  { id: 'VOID', icon: 'flare', tone: 'Ethereal' },
  { id: 'STORM', icon: 'thunderstorm', tone: 'Volatile' },
  { id: 'CROWN', icon: 'workspace_premium', tone: 'Political' },
  { id: 'KNOWLEDGE', icon: 'menu_book', tone: 'Scholarly' },
  { id: 'SHADOW', icon: 'nights_stay', tone: 'Mysterious' },
  { id: 'WAR', icon: 'swords', tone: 'Brutal' },
  { id: 'PEACE', icon: 'volunteer_activism', tone: 'Serene' },
  { id: 'TIME', icon: 'history', tone: 'Eternal' },
  { id: 'CHAOS', icon: 'cyclone', tone: 'Erratic' },
  { id: 'ORDER', icon: 'balance', tone: 'Rigid' },
  { id: 'MAGIC', icon: 'auto_fix_high', tone: 'Arcane' },
  { id: 'DEATH', icon: 'skull', tone: 'Somber' },
  { id: 'LOVE', icon: 'favorite', tone: 'Romantic' },
  { id: 'HATE', icon: 'heart_broken', tone: 'Bitter' },
  { id: 'MACHINES', icon: 'settings', tone: 'Steampunk' },
  { id: 'OCEANS', icon: 'tsunami', tone: 'Nautical' },
  { id: 'DESERTS', icon: 'wb_sunny', tone: 'Harsh' },
  { id: 'MOUNTAINS', icon: 'landscape', tone: 'Stony' },
  { id: 'SKY', icon: 'cloud', tone: 'Airy' },
  { id: 'BLOOD', icon: 'bloodtype', tone: 'Primal' },
  { id: 'BONES', icon: 'format_color_fill', tone: 'Skeletal' },
  { id: 'ART', icon: 'palette', tone: 'Creative' },
  { id: 'MUSIC', icon: 'music_note', tone: 'Harmonic' },
  { id: 'WINTER', icon: 'ac_unit', tone: 'Chilly' },
  { id: 'SUMMER', icon: 'sunny', tone: 'Blazing' },
  { id: 'SPRING', icon: 'spa', tone: 'Blooming' },
  { id: 'AUTUMN', icon: 'energy_savings_leaf', tone: 'Golden' },
  { id: 'SECRETS', icon: 'key', tone: 'Cloaked' },
  { id: 'TRUTH', icon: 'visibility', tone: 'Piercing' },
  { id: 'LIES', icon: 'record_voice_over', tone: 'Deceptive' },
  { id: 'DREAMS', icon: 'bedtime', tone: 'Ethereal' },
  { id: 'NIGHTMARES', icon: 'dangerous', tone: 'Terrifying' },
  { id: 'PLENTY', icon: 'inventory_2', tone: 'Bountiful' },
  { id: 'FAMINE', icon: 'humidity_low', tone: 'Starving' },
  { id: 'JUSTICE', icon: 'gavel', tone: 'Stern' },
  { id: 'TRICKERY', icon: 'mask', tone: 'Playful' },
  { id: 'BEAUTY', icon: 'auto_awesome', tone: 'Radiant' },
  { id: 'UGLINESS', icon: 'sick', tone: 'Grotesque' },
  { id: 'FATE', icon: 'architecture', tone: 'Deterministic' },
  { id: 'WILL', icon: 'bolt', tone: 'Determined' },
  { id: 'ANIMALS', icon: 'pets', tone: 'Feral' },
  { id: 'PLANTS', icon: 'potted_plant', tone: 'Botanical' },
  { id: 'COMMERCE', icon: 'payments', tone: 'Mercenary' },
  { id: 'SILENCE', icon: 'volume_off', tone: 'Muted' },
  { id: 'NOISE', icon: 'volume_up', tone: 'Loud' },
  { id: 'MADNESS', icon: 'psychology', tone: 'Fractured' },
  { id: 'SANITY', icon: 'self_improvement', tone: 'Calm' },
  { id: 'LUXURY', icon: 'diamond', tone: 'Opulent' },
  { id: 'POVERTY', icon: 'front_hand', tone: 'Humble' },
  { id: 'HUNT', icon: 'track_changes', tone: 'Predatory' },
  { id: 'HARVEST', icon: 'agriculture', tone: 'Fertile' },
  { id: 'ARCHITECTURE', icon: 'castle', tone: 'Structured' },
  { id: 'MEDICINE', icon: 'medical_services', tone: 'Healing' },
  { id: 'PLAGUE', icon: 'coronavirus', tone: 'Viral' },
  { id: 'TRAVEL', icon: 'flight', tone: 'Mobile' },
  { id: 'HOME', icon: 'house', tone: 'Cozy' },
  { id: 'MEMORY', icon: 'memory', tone: 'Nostalgic' },
  { id: 'OBLIVION', icon: 'brightness_empty', tone: 'Erasing' },
  { id: 'PRIDE', icon: 'military_tech', tone: 'Arrogant' },
  { id: 'GREED', icon: 'paid', tone: 'Hoarding' },
  { id: 'LUST', icon: 'favorite_border', tone: 'Desiring' },
  { id: 'ENVY', icon: 'visibility_off', tone: 'Covetous' },
  { id: 'GLUTTONY', icon: 'restaurant', tone: 'Devouring' },
  { id: 'WRATH', icon: 'back_hand', tone: 'Angry' },
  { id: 'SLOTH', icon: 'bed', tone: 'Lazy' },
  { id: 'REBIRTH', icon: 'cached', tone: 'Cyclical' },
  { id: 'DECAY', icon: 'delete_outline', tone: 'Rotting' },
  { id: 'LIGHTNING', icon: 'flash_on', tone: 'Shocking' },
  { id: 'ICE', icon: 'severe_cold', tone: 'Glacial' },
  { id: 'RADIANCE', icon: 'wb_iridescent', tone: 'Holy' },
  { id: 'MIRROR', icon: 'content_copy', tone: 'Reflective' },
  { id: 'ECHO', icon: 'settings_voice', tone: 'Resonating' },
  { id: 'THRESHOLD', icon: 'door_open', tone: 'Liminal' },
  { id: 'LABYRINTH', icon: 'view_quilt', tone: 'Confusing' },
  { id: 'GRAVITY', icon: 'south', tone: 'Heavy' },
  { id: 'LEVITY', icon: 'north', tone: 'Light' },
  { id: 'IRON', icon: 'hardware', tone: 'Metallic' },
  { id: 'GOLD', icon: 'monetization_on', tone: 'Wealthy' },
  { id: 'CLAY', icon: 'format_paint', tone: 'Malleable' },
  { id: 'GLASS', icon: 'blur_on', tone: 'Transparent' },
  { id: 'VOID_WALK', icon: 'directions_run', tone: 'Eerie' },
  { id: 'SUPERNOVA', icon: 'star', tone: 'Cosmic' },
];

export const SUGGESTED_NAMES = ['Aethelgard', 'Orynthia', 'Kaldor', 'Zenthos', 'Myr', 'Valoria', 'Eos', 'Hyperion'];
