import type { SymmetryDefinition, SymmetryId } from "./types";

export const SYMMETRY_DEFINITIONS: Record<SymmetryId, SymmetryDefinition> = {
  none: {
    symmetryId: "none",
    displayName: "None (Asymmetric)",
    description: "No symmetry transform",
    category: "none",
    foldCount: 1,
    mirrorCount: 0,
    phase: 1,
  },
  "mirror-v": {
    symmetryId: "mirror-v",
    displayName: "Mirror Vertical",
    description: "Left-right reflection",
    category: "mirror",
    foldCount: 1,
    mirrorCount: 1,
    phase: 1,
  },
  "mirror-h": {
    symmetryId: "mirror-h",
    displayName: "Mirror Horizontal",
    description: "Top-bottom reflection",
    category: "mirror",
    foldCount: 1,
    mirrorCount: 1,
    phase: 1,
  },
  "mirror-vh": {
    symmetryId: "mirror-vh",
    displayName: "Mirror Vertical + Horizontal",
    description: "Four mirrored quadrants",
    category: "mirror",
    foldCount: 2,
    mirrorCount: 2,
    phase: 1,
  },
  "rot-4": {
    symmetryId: "rot-4",
    displayName: "4-Fold Rotation",
    description: "90 degree rotational symmetry",
    category: "rotational",
    foldCount: 4,
    mirrorCount: 0,
    phase: 1,
  },
  "rot-2": {
    symmetryId: "rot-2",
    displayName: "2-Fold Rotation",
    description: "180 degree rotational symmetry",
    category: "rotational",
    foldCount: 2,
    mirrorCount: 0,
    phase: 2,
  },
  "rot-3": {
    symmetryId: "rot-3",
    displayName: "3-Fold Rotation",
    description: "120 degree rotational symmetry",
    category: "rotational",
    foldCount: 3,
    mirrorCount: 0,
    phase: 2,
  },
  "rot-6": {
    symmetryId: "rot-6",
    displayName: "6-Fold Rotation",
    description: "60 degree rotational symmetry",
    category: "rotational",
    foldCount: 6,
    mirrorCount: 0,
    phase: 2,
  },
  "rot-8": {
    symmetryId: "rot-8",
    displayName: "8-Fold Rotation",
    description: "45 degree rotational symmetry",
    category: "rotational",
    foldCount: 8,
    mirrorCount: 0,
    phase: 1,
  },
  "radial-4": {
    symmetryId: "radial-4",
    displayName: "Radial 4-Way",
    description: "Four-way radial arrangement",
    category: "radial",
    foldCount: 4,
    mirrorCount: 4,
    phase: 2,
  },
  "radial-6": {
    symmetryId: "radial-6",
    displayName: "Radial 6-Way",
    description: "Six-way radial arrangement",
    category: "radial",
    foldCount: 6,
    mirrorCount: 6,
    phase: 2,
  },
  "radial-8": {
    symmetryId: "radial-8",
    displayName: "Radial 8-Way",
    description: "Eight-way radial arrangement with rays",
    category: "radial",
    foldCount: 8,
    mirrorCount: 8,
    phase: 1,
  },
  "radial-12": {
    symmetryId: "radial-12",
    displayName: "Radial 12-Way",
    description: "Twelve-way radial arrangement",
    category: "radial",
    foldCount: 12,
    mirrorCount: 12,
    phase: 2,
  },
  "radial-16": {
    symmetryId: "radial-16",
    displayName: "Radial 16-Way",
    description: "Sixteen-way radial arrangement",
    category: "radial",
    foldCount: 16,
    mirrorCount: 16,
    phase: 2,
  },
  "hybrid-quad": {
    symmetryId: "hybrid-quad",
    displayName: "Hybrid Quad Mirror",
    description: "4-way with mirror + rotation blend",
    category: "hybrid",
    foldCount: 4,
    mirrorCount: 2,
    phase: 3,
  },
  "hybrid-hex": {
    symmetryId: "hybrid-hex",
    displayName: "Hybrid Hex Mirror",
    description: "6-way with tri-rotation and mirrors",
    category: "hybrid",
    foldCount: 6,
    mirrorCount: 3,
    phase: 3,
  },
  "hybrid-tri": {
    symmetryId: "hybrid-tri",
    displayName: "Hybrid Tri Mirror",
    description: "Triquetra-like mirrored tri-rotation",
    category: "hybrid",
    foldCount: 6,
    mirrorCount: 3,
    phase: 3,
  },
  "hybrid-oct": {
    symmetryId: "hybrid-oct",
    displayName: "Hybrid Oct Mirror",
    description: "8-way with rotation and mirror structure",
    category: "hybrid",
    foldCount: 8,
    mirrorCount: 8,
    phase: 3,
  },
};

export const PHASE_1_SYMMETRY_IDS: SymmetryId[] = [
  "none",
  "mirror-v",
  "mirror-h",
  "mirror-vh",
  "rot-4",
  "rot-8",
  "radial-8",
];

export const PHASE_2_SYMMETRY_IDS: SymmetryId[] = [
  "rot-2",
  "rot-3",
  "rot-6",
  "radial-4",
  "radial-6",
  "radial-12",
  "radial-16",
];

export const SUPPORTED_SYMMETRY_IDS: SymmetryId[] = [
  ...PHASE_1_SYMMETRY_IDS,
  ...PHASE_2_SYMMETRY_IDS,
  "hybrid-quad",
  "hybrid-hex",
  "hybrid-tri",
  "hybrid-oct",
];

export const PHASE_3_SYMMETRY_IDS: SymmetryId[] = [
  "hybrid-quad",
  "hybrid-hex",
  "hybrid-tri",
  "hybrid-oct",
];

export function getSymmetryDefinition(symmetryId: SymmetryId): SymmetryDefinition {
  return SYMMETRY_DEFINITIONS[symmetryId];
}
