// =============================================================================
// MythosForge - Calendar Forge: Brainstorming Wizard Configuration
// =============================================================================

/**
 * Structured calendar data — populated by the AI Synthesizer pipeline.
 * These are the hard integers and arrays the visual calendar UI needs.
 */
export interface CalendarStructuredData {
  total_months: number;
  days_per_week: number;
  days_per_month: number;
  intercalary_days_count: number;
  month_names: string[];
  weekday_names: string[];
  epoch_event: string;
}

/**
 * Full CalendarAttributes stored in json_attributes on a Calendar entity.
 * - design_notes: the raw brainstorming text (user-authored)
 * - synthesized: the AI-extracted structured integers/arrays
 */
import type { CalendarEvent, CalendarEventCategory, CalendarSeason } from './calendar-types';

export interface CalendarAttributes {
  design_notes: {
    cosmology_solar: string;
    cosmology_moons: string;
    structure_grid: string;
    structure_intercalary: string;
    lore_epoch: string;
    lore_naming: string;
  };
  synthesized?: CalendarStructuredData;
  events?: CalendarEvent[];
  seasons?: CalendarSeason[];
}

export type { CalendarEvent, CalendarSeason, CalendarEventCategory };
export { DEFAULT_SEASONS } from './calendar-types';

export interface CalendarPrompt {
  id: keyof CalendarAttributes['design_notes'];
  title: string;
  question: string;
  suggestions: string[];
}

/**
 * The 6 brainstorming categories for the Hybrid Calendar Forge.
 * Each prompt maps to a key in CalendarAttributes.design_notes.
 */
export const CALENDAR_PROMPTS: CalendarPrompt[] = [
  {
    id: 'cosmology_solar',
    title: '1. Cosmology — Solar Year',
    question: 'How long is the solar year, and what drives the seasons?',
    suggestions: [
      '365 days, standard axial tilt',
      '300 days, fast orbit with short intense seasons',
      '400+ days, long orbit causing multi-year winters',
    ],
  },
  {
    id: 'cosmology_moons',
    title: '2. Cosmology — Moons',
    question: 'How many moons exist, and how do they affect the world?',
    suggestions: [
      'One moon with a standard 30-day phase',
      'Two moons with overlapping tides',
      'A shattered moon ring that rains arcane debris',
    ],
  },
  {
    id: 'structure_grid',
    title: '3. Structure — The Grid',
    question: 'How are months and weeks divided?',
    suggestions: [
      '12 uniform months, 7-day weeks',
      '10 decimal months, 10-day tendays',
      '13 lunar months with alternating lengths',
    ],
  },
  {
    id: 'structure_intercalary',
    title: '4. Structure — Intercalary Days',
    question: 'Are there days that exist entirely outside the normal calendar grid?',
    suggestions: [
      'None, a perfect grid',
      'A single New Year festival day outside any month',
      'Five dead days at the end of the year where magic fails',
    ],
  },
  {
    id: 'lore_epoch',
    title: '5. Lore — The Epoch',
    question: 'What exact event marks Year 1 of the current era?',
    suggestions: [
      'The Sundering (A global cataclysm)',
      'The Unification of the First Empire',
      'The Death of the Prime Deity',
    ],
  },
  {
    id: 'lore_naming',
    title: '6. Lore — Naming Conventions',
    question: 'What is the thematic origin of the month and day names?',
    suggestions: [
      'Agricultural cycles (e.g., Harvest, Frost)',
      'The Pantheon of Gods',
      'Historical Emperors and Heroes',
    ],
  },
];

/**
 * Build a human-readable markdown document from the forge brainstorming
 * data. This gets saved into the entity's markdown_content.
 */
export function buildCalendarMarkdown(designNotes: CalendarAttributes['design_notes']): string {
  const promptMap = new Map(CALENDAR_PROMPTS.map((p) => [p.id, p]));
  const sections: string[] = ['# Calendar Design\n'];

  for (const [key, value] of Object.entries(designNotes)) {
    const prompt = promptMap.get(key as keyof typeof designNotes);
    const heading = prompt?.title ?? key.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
    const question = prompt?.question ?? '';
    sections.push(`## ${heading}\n`);
    if (question) sections.push(`*${question}*\n`);
    sections.push(`${value || '*Not yet defined.*'}\n`);
  }

  sections.push('---\n');
  sections.push('*Generated by the Hybrid Calendar Forge — MythosForge*\n');
  return sections.join('\n');
}

/**
 * Build the complete markdown including synthesized calendar data table.
 * Used by both the AI save path and the manual save path.
 */
export function buildFinalMarkdown(
  designNotes: CalendarAttributes['design_notes'],
  data: CalendarStructuredData,
): string {
  const base = buildCalendarMarkdown(designNotes);
  const synthesized = [
    '## Synthesized Calendar Structure', '',
    '| Property | Value |', '|---|---|',
    `| Total Months | ${data.total_months} |`,
    `| Days per Week | ${data.days_per_week} |`,
    `| Days per Month | ${data.days_per_month} |`,
    `| Intercalary Days | ${data.intercalary_days_count} |`, '',
    `**Months:** ${data.month_names.join(', ')}`, '',
    `**Weekdays:** ${data.weekday_names.join(', ')}`, '',
    `**Epoch Event:** ${data.epoch_event}`, '',
    '---', '*Calendar data synthesized — MythosForge*',
  ].join('\n');
  return `${base}\n\n${synthesized}`;
}
